'use strict';

const TEMPS_HEURE = 1000;
const TEMPS_ATTENTE = 2 * 1000;
const NOMBRE_CLIENT_CREE_MIN = 3;
const NOMBRE_CLIENT_CREE_MAX = 5;
const TEMPS_PREPARATION_MIN = 5;
const TEMPS_PREPARATION_MAX = 50;
// horloge
const NOMBRE_DE_RECETTE_MIN = 3;
const NOMBRE_DE_RECETTE_MAX = 5;
const NOMBRE_TYPE_INGREDIENT = 5;
const NOMBRE_INGREDIENT_MIN_RECETTE = 0;
const NOMBRE_INGREDIENT_MAX_RECETTE = 1;
const TEMPS_ATTENTE_MIN_RAVITAILLEMENT = 15;
const TEMPS_ATTENTE_MAX_RAVITAILLEMENT = 115;
const NOMBRE_INGREDIENT = 10;
const STOCK_DEPART = 20;
const  STOCK_DESIRE = 20;
const SEUIL_CRITIQUE = 5;
// Client
const SEUIL_RESISTANCE_MIN = 10;
const SEUIL_RESISTANCE_MAX = 10;

module.exports ={
  TEMPS_HEURE : TEMPS_HEURE,
  TEMPS_ATTENTE : TEMPS_ATTENTE,
  NOMBRE_CLIENT_CREE_MIN : NOMBRE_CLIENT_CREE_MIN,
  NOMBRE_CLIENT_CREE_MAX : NOMBRE_CLIENT_CREE_MAX,
  TEMPS_PREPARATION_MIN : TEMPS_PREPARATION_MIN, // Correspond à 5 minutes dans notre horloge
  TEMPS_PREPARATION_MAX : TEMPS_PREPARATION_MAX,// Correspond à 50 minutes dans notre
// horloge
  NOMBRE_DE_RECETTE_MIN : NOMBRE_DE_RECETTE_MIN,
  NOMBRE_DE_RECETTE_MAX : NOMBRE_DE_RECETTE_MAX,
  NOMBRE_TYPE_INGREDIENT : NOMBRE_TYPE_INGREDIENT,
  NOMBRE_INGREDIENT_MIN_RECETTE : NOMBRE_INGREDIENT_MIN_RECETTE,
  NOMBRE_INGREDIENT_MAX_RECETTE : NOMBRE_INGREDIENT_MAX_RECETTE,
  TEMPS_ATTENTE_MIN_RAVITAILLEMENT : TEMPS_ATTENTE_MIN_RAVITAILLEMENT,
  TEMPS_ATTENTE_MAX_RAVITAILLEMENT : TEMPS_ATTENTE_MAX_RAVITAILLEMENT,
  NOMBRE_INGREDIENT : NOMBRE_INGREDIENT,
  STOCK_DEPART : STOCK_DEPART,
  STOCK_DESIRE : STOCK_DESIRE,
  SEUIL_CRITIQUE : SEUIL_CRITIQUE,
  // Client
  SEUIL_RESISTANCE_MIN : SEUIL_RESISTANCE_MIN,
  SEUIL_RESISTANCE_MAX : SEUIL_RESISTANCE_MAX
};
